/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorproject;
import java.text.DecimalFormat;
import java.awt.Font;
import javax.swing.JOptionPane;


/**
 *
 * @author George Somoso - Java Project
 */

public class CalculatorExtendedView extends javax.swing.JFrame {

    DecimalFormat df;
    Calculate calc = new Calculate();
    public boolean isDegrees = true;
    /**
     * Creates new form CalculatorBasicView
     */
    public CalculatorExtendedView() {
        initComponents();
        displayReset();
        
    }
    
    /**
     * Reset Screen
     */
    public final void displayReset(){
        txtMainScreen.setVisible(false);
        txtAnswerScreen.setVisible(true);
        txtAnswerScreen.setText("0");
    }
    
    /**
     * Answer Screen Method for Display
     */
    public void displayAns(){
        txtMainScreen.setVisible(false);
        txtAnswerScreen.setVisible(true);
        txtAnswerScreen.setText(String.valueOf(calc.getNum1()));
    }
    
    /**
     * DIsplays the input and removes the answers from screen.
     */
    public void displayInput(){
        txtAnswerScreen.setVisible(false);
        txtMainScreen.setVisible(true);
    }
    
    /**
     * Rounding
     */
    public void doRounding(){
        txtMainScreen.setText(String.valueOf(df.format(calc.getAnswer())));
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuViewButtonGroup = new javax.swing.ButtonGroup();
        mnuFontButtonGroup = new javax.swing.ButtonGroup();
        mnuRoundButtonGroup = new javax.swing.ButtonGroup();
        radbtnDegreeRad = new javax.swing.ButtonGroup();
        dlgHotKeys = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        txtMainScreen = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnFraction = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNegative = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        rbtnDegrees = new javax.swing.JRadioButton();
        rbtnRadians = new javax.swing.JRadioButton();
        btnSin = new javax.swing.JButton();
        btnASin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnACos = new javax.swing.JButton();
        btnATan = new javax.swing.JButton();
        btnEula = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        txtAnswerScreen = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        mnuViewBasic = new javax.swing.JRadioButtonMenuItem();
        mnuViewExtended = new javax.swing.JRadioButtonMenuItem();
        mnuFont = new javax.swing.JMenu();
        mnuFontPlain = new javax.swing.JRadioButtonMenuItem();
        mnuFontBold = new javax.swing.JRadioButtonMenuItem();
        mnuRound = new javax.swing.JMenu();
        mnuRound0 = new javax.swing.JRadioButtonMenuItem();
        mnuRound1 = new javax.swing.JRadioButtonMenuItem();
        mnuRound2 = new javax.swing.JRadioButtonMenuItem();
        mnuRound3 = new javax.swing.JRadioButtonMenuItem();
        mnuRound4 = new javax.swing.JRadioButtonMenuItem();
        mnuRound5 = new javax.swing.JRadioButtonMenuItem();
        mnuRound6 = new javax.swing.JRadioButtonMenuItem();
        mnuRound7 = new javax.swing.JRadioButtonMenuItem();
        mnuRound8 = new javax.swing.JRadioButtonMenuItem();
        mnuRound9 = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuHelpAbout = new javax.swing.JMenuItem();
        mnuHelpHotKeys = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 350, 460));
        setLocation(location());
        setResizable(false);
        setSize(new java.awt.Dimension(350, 450));
        getContentPane().setLayout(null);

        txtMainScreen.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtMainScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMainScreen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMainScreen.setEnabled(false);
        getContentPane().add(txtMainScreen);
        txtMainScreen.setBounds(10, 20, 333, 50);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(12, 108, 61, 48);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(80, 108, 61, 48);

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiply);
        btnMultiply.setBounds(216, 108, 61, 48);

        btnFraction.setText("1/x");
        btnFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFractionActionPerformed(evt);
            }
        });
        getContentPane().add(btnFraction);
        btnFraction.setBounds(284, 108, 61, 48);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(148, 108, 61, 48);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(12, 163, 61, 48);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(80, 163, 61, 48);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(148, 163, 61, 48);

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide);
        btnDivide.setBounds(216, 163, 61, 48);

        btnPower.setText("x^y");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });
        getContentPane().add(btnPower);
        btnPower.setBounds(284, 163, 61, 48);

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(216, 218, 61, 48);

        btnNegative.setText("+/-");
        btnNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegativeActionPerformed(evt);
            }
        });
        getContentPane().add(btnNegative);
        btnNegative.setBounds(282, 218, 61, 48);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(12, 218, 61, 48);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(80, 218, 61, 48);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(148, 218, 61, 48);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(12, 273, 61, 48);

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoint);
        btnPoint.setBounds(80, 273, 61, 48);

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquals);
        btnEquals.setBounds(148, 273, 61, 48);

        btnFactorial.setText("x!");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnFactorial);
        btnFactorial.setBounds(282, 273, 61, 48);

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinus);
        btnMinus.setBounds(214, 273, 61, 48);

        btnCA.setText("CA");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });
        getContentPane().add(btnCA);
        btnCA.setBounds(12, 351, 134, 45);

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE);
        btnCE.setBounds(153, 351, 129, 45);

        radbtnDegreeRad.add(rbtnDegrees);
        rbtnDegrees.setSelected(true);
        rbtnDegrees.setText("Degrees");
        rbtnDegrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDegreesActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDegrees);
        rbtnDegrees.setBounds(376, 22, 75, 25);

        radbtnDegreeRad.add(rbtnRadians);
        rbtnRadians.setText("Radians");
        rbtnRadians.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnRadiansStateChanged(evt);
            }
        });
        rbtnRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRadiansActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnRadians);
        rbtnRadians.setBounds(469, 22, 73, 25);

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        getContentPane().add(btnSin);
        btnSin.setBounds(384, 108, 61, 48);

        btnASin.setText("asin");
        btnASin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASinActionPerformed(evt);
            }
        });
        getContentPane().add(btnASin);
        btnASin.setBounds(463, 108, 66, 48);

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCos);
        btnCos.setBounds(384, 163, 61, 48);

        btnACos.setText("acos");
        btnACos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACosActionPerformed(evt);
            }
        });
        getContentPane().add(btnACos);
        btnACos.setBounds(463, 163, 66, 48);

        btnATan.setText("atan");
        btnATan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATanActionPerformed(evt);
            }
        });
        getContentPane().add(btnATan);
        btnATan.setBounds(463, 218, 66, 48);

        btnEula.setText("E");
        btnEula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEula);
        btnEula.setBounds(463, 273, 66, 48);

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTan);
        btnTan.setBounds(384, 218, 61, 48);

        btnPI.setText("PI");
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });
        getContentPane().add(btnPI);
        btnPI.setBounds(384, 273, 61, 48);

        txtAnswerScreen.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtAnswerScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAnswerScreen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAnswerScreen.setEnabled(false);
        getContentPane().add(txtAnswerScreen);
        txtAnswerScreen.setBounds(10, 20, 330, 50);

        mnuView.setText("View");

        mnuViewBasic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        mnuViewButtonGroup.add(mnuViewBasic);
        mnuViewBasic.setSelected(true);
        mnuViewBasic.setText("Basic");
        mnuViewBasic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mnuViewBasicStateChanged(evt);
            }
        });
        mnuViewBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewBasicActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewBasic);

        mnuViewExtended.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        mnuViewButtonGroup.add(mnuViewExtended);
        mnuViewExtended.setText("Extended");
        mnuViewExtended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewExtendedActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewExtended);

        jMenuBar1.add(mnuView);

        mnuFont.setText("Font");

        mnuFontPlain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuFontButtonGroup.add(mnuFontPlain);
        mnuFontPlain.setSelected(true);
        mnuFontPlain.setText("Plain");
        mnuFontPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFontPlainActionPerformed(evt);
            }
        });
        mnuFont.add(mnuFontPlain);

        mnuFontBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuFontButtonGroup.add(mnuFontBold);
        mnuFontBold.setText("Bold");
        mnuFontBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFontBoldActionPerformed(evt);
            }
        });
        mnuFont.add(mnuFontBold);

        jMenuBar1.add(mnuFont);

        mnuRound.setText("Round");

        mnuRoundButtonGroup.add(mnuRound0);
        mnuRound0.setText("0");
        mnuRound0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound0ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound0);

        mnuRoundButtonGroup.add(mnuRound1);
        mnuRound1.setText("1");
        mnuRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound1ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound1);

        mnuRoundButtonGroup.add(mnuRound2);
        mnuRound2.setText("2");
        mnuRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound2ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound2);

        mnuRoundButtonGroup.add(mnuRound3);
        mnuRound3.setText("3");
        mnuRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound3ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound3);

        mnuRoundButtonGroup.add(mnuRound4);
        mnuRound4.setText("4");
        mnuRound4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound4ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound4);

        mnuRoundButtonGroup.add(mnuRound5);
        mnuRound5.setText("5");
        mnuRound5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound5ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound5);

        mnuRoundButtonGroup.add(mnuRound6);
        mnuRound6.setText("6");
        mnuRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound6ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound6);

        mnuRoundButtonGroup.add(mnuRound7);
        mnuRound7.setText("7");
        mnuRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound7ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound7);

        mnuRoundButtonGroup.add(mnuRound8);
        mnuRound8.setText("8");
        mnuRound8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound8ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound8);

        mnuRoundButtonGroup.add(mnuRound9);
        mnuRound9.setSelected(true);
        mnuRound9.setText("9");
        mnuRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRound9ActionPerformed(evt);
            }
        });
        mnuRound.add(mnuRound9);

        jMenuBar1.add(mnuRound);

        mnuHelp.setText("Help");

        mnuHelpAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        mnuHelpAbout.setText("About");
        mnuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHelpAbout);

        mnuHelpHotKeys.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        mnuHelpHotKeys.setText("Hot Keys");
        mnuHelpHotKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpHotKeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHelpHotKeys);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuViewBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewBasicActionPerformed
        // TODO add your handling code here:
        this.setSize(360,480);
        
    }//GEN-LAST:event_mnuViewBasicActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void mnuViewBasicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mnuViewBasicStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuViewBasicStateChanged

    private void mnuViewExtendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewExtendedActionPerformed
        // TODO add your handling code here:
        this.setSize(560,480);
    }//GEN-LAST:event_mnuViewExtendedActionPerformed

    private void mnuFontPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFontPlainActionPerformed
        // TODO add your handling code here:
        txtMainScreen.setFont(txtMainScreen.getFont().deriveFont(Font.PLAIN));
        
    }//GEN-LAST:event_mnuFontPlainActionPerformed

    private void mnuFontBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFontBoldActionPerformed
        // TODO add your handling code here:
        txtMainScreen.setFont(txtMainScreen.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_mnuFontBoldActionPerformed

    private void mnuRound0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound0ActionPerformed
        // Round Figures on the Screen to 0 Decimal Places
        df = new DecimalFormat("#");
        doRounding();
    }//GEN-LAST:event_mnuRound0ActionPerformed

    private void mnuRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound1ActionPerformed
        // Round Figures on the Screen to 1 Decimal Places
        df = new DecimalFormat("#.#");
        doRounding();
    }//GEN-LAST:event_mnuRound1ActionPerformed

    private void mnuRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound2ActionPerformed
        // Round Figures on the Screen to 2 Decimal Places
        df = new DecimalFormat("#.##");
        doRounding();
    }//GEN-LAST:event_mnuRound2ActionPerformed

    private void mnuRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound3ActionPerformed
        // Round Figures on the Screen to 3 Decimal Places
        df = new DecimalFormat("#.###");
        doRounding();
    }//GEN-LAST:event_mnuRound3ActionPerformed

    private void mnuRound4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound4ActionPerformed
       // Round Figures on the Screen to 4 Decimal Places
        df = new DecimalFormat("#.####");
        doRounding();
    }//GEN-LAST:event_mnuRound4ActionPerformed

    private void mnuRound5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound5ActionPerformed
        // Round Figures on the Screen to 5 Decimal Places
        df = new DecimalFormat("#.#####");
        doRounding();
    }//GEN-LAST:event_mnuRound5ActionPerformed

    private void mnuRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound6ActionPerformed
        // Round Figures on the Screen to 6 Decimal Places
        df = new DecimalFormat("#.######");
        doRounding();
    }//GEN-LAST:event_mnuRound6ActionPerformed

    private void mnuRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound7ActionPerformed
        // Round Figures on the Screen to 7 Decimal Places
        df = new DecimalFormat("#.#######");
        doRounding();
    }//GEN-LAST:event_mnuRound7ActionPerformed

    private void mnuRound8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound8ActionPerformed
        // Round Figures on the Screen to 8 Decimal Places
        df = new DecimalFormat("#.########");
        doRounding();
    }//GEN-LAST:event_mnuRound8ActionPerformed

    private void mnuRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRound9ActionPerformed
        // Round Figures on the Screen to 9 Decimal Places
        df = new DecimalFormat("#.#########");
        doRounding();
    }//GEN-LAST:event_mnuRound9ActionPerformed

    private void mnuHelpHotKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpHotKeysActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "<html>A - About<br>K - Hot Keys<br>Ctrl-P - Plain Font<br>"
                + "Ctrl+B - Bold Font<br>B - Basic View<br>E - Extended View<br>Alt+P - PI"
                + "Alt+E - Eula Number (e)", "HotKeys",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHelpHotKeysActionPerformed

    private void mnuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Calculator v1.1 \r\nCreated by: Draggem \r\nUpdated: 11/10/2019", "About",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHelpAboutActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"1");  
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        displayInput();
        txtMainScreen.setText(txtMainScreen.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        // TODO add your handling code here:
        txtMainScreen.setText("");
        displayReset();
        calc.reset();
        
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        //txtMainScreen.setText(txtMainScreen.getText().substring(0,txtMainScreen.getText().length()-1));
        txtMainScreen.setText("");
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
        if (txtMainScreen.getText().contains(".")){
            System.out.println("already a . there");
            txtMainScreen.setText("THe number cannot have multiple decimal points");
        }
        else{
            txtMainScreen.setText(txtMainScreen.getText()+".");
        }
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText())+ calc.getNum1());
        calc.setOp('-');
        displayAns();
        txtMainScreen.setText("");}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText())+ calc.getNum1());
        calc.setOp('+');
        displayAns();
        txtMainScreen.setText("");}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum2(Double.parseDouble(txtMainScreen.getText()));
        calc.calculate();
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));
        calc.setNum2(calc.getNum1());
        calc.setNum1(0);}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        

    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        try{
            calc.setNum1(Double.parseDouble(txtMainScreen.getText()) + calc.getNum1());
            calc.setOp('/');
            displayAns();
            txtMainScreen.setText("");
        }catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        try{
            calc.setNum1(Double.parseDouble(txtMainScreen.getText())+ calc.getNum1());
            calc.setOp('*');
            displayAns();
            txtMainScreen.setText(""); 
        }
        
        
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        

    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void rbtnDegreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDegreesActionPerformed
        // TODO add your handling code here:
        isDegrees = true;
        
    }//GEN-LAST:event_rbtnDegreesActionPerformed

    private void rbtnRadiansStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnRadiansStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbtnRadiansStateChanged

    private void rbtnRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRadiansActionPerformed
        // TODO add your handling code here:
        isDegrees = false;
        
    }//GEN-LAST:event_rbtnRadiansActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("sin", isDegrees);
        
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("cos", isDegrees);
        
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("tan", isDegrees);
        
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnASinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASinActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("asin", isDegrees);
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnASinActionPerformed

    private void btnACosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACosActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("acos", isDegrees);
        
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnACosActionPerformed

    private void btnATanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATanActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        calc.extendedOperations("atan", isDegrees);
        
        txtMainScreen.setText(String.valueOf(calc.getAnswer()));}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnATanActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
        // TODO add your handling code here:
        txtMainScreen.setText(String.valueOf(Calculate.getPI()));
    }//GEN-LAST:event_btnPIActionPerformed

    private void btnEulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEulaActionPerformed
        // TODO add your handling code here:
        txtMainScreen.setText(String.valueOf(Calculate.getE()));
    }//GEN-LAST:event_btnEulaActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()) + calc.getNum1());
        calc.setOp('p');
        txtMainScreen.setText("");}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFractionActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        txtMainScreen.setText(calc.fraction());}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFractionActionPerformed

    private void btnNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegativeActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        txtMainScreen.setText(calc.opposites());}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNegativeActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        // TODO add your handling code here:
        try{
        calc.setNum1(Double.parseDouble(txtMainScreen.getText()));
        txtMainScreen.setText(calc.factorial());}
        catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(null,
                "Error: You must enter an integer0" + nfe);

       } catch (ArithmeticException ae) {
          JOptionPane.showMessageDialog(null,
                "Error!" + ae);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: Invalid Input", "Error |0|0|||0|",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnFactorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorExtendedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorExtendedView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnACos;
    private javax.swing.JButton btnASin;
    private javax.swing.JButton btnATan;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnEula;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFraction;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNegative;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.JOptionPane dlgHotKeys;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JRadioButtonMenuItem mnuFontBold;
    private javax.swing.ButtonGroup mnuFontButtonGroup;
    private javax.swing.JRadioButtonMenuItem mnuFontPlain;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelpAbout;
    private javax.swing.JMenuItem mnuHelpHotKeys;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JRadioButtonMenuItem mnuRound0;
    private javax.swing.JRadioButtonMenuItem mnuRound1;
    private javax.swing.JRadioButtonMenuItem mnuRound2;
    private javax.swing.JRadioButtonMenuItem mnuRound3;
    private javax.swing.JRadioButtonMenuItem mnuRound4;
    private javax.swing.JRadioButtonMenuItem mnuRound5;
    private javax.swing.JRadioButtonMenuItem mnuRound6;
    private javax.swing.JRadioButtonMenuItem mnuRound7;
    private javax.swing.JRadioButtonMenuItem mnuRound8;
    private javax.swing.JRadioButtonMenuItem mnuRound9;
    private javax.swing.ButtonGroup mnuRoundButtonGroup;
    private javax.swing.JMenu mnuView;
    private javax.swing.JRadioButtonMenuItem mnuViewBasic;
    private javax.swing.ButtonGroup mnuViewButtonGroup;
    private javax.swing.JRadioButtonMenuItem mnuViewExtended;
    private javax.swing.ButtonGroup radbtnDegreeRad;
    private javax.swing.JRadioButton rbtnDegrees;
    private javax.swing.JRadioButton rbtnRadians;
    private javax.swing.JTextField txtAnswerScreen;
    private javax.swing.JTextField txtMainScreen;
    // End of variables declaration//GEN-END:variables
}
